server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres

