name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Give exec permissions to gradlew
      run: chmod +x ./gradlew

    - name: Config Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' 
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Build Docker image
      run: |
        docker build -t fabianyr/wallet:latest .

    - name: Install SSH Client
      run: sudo apt-get install -y ssh-client

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Transfer Docker image to EC2
        docker save fabianyr/wallet:latest | gzip -c > wallet.tar.gz
        scp -i private_key.pem wallet.tar.gz $USERNAME@$HOST:~/

        # Commands to run on EC2
        ssh -i private_key.pem $USERNAME@$HOST "
          docker load -i ~/wallet.tar.gz
          docker container stop wallet-container || true
          docker container rm wallet-container || true
          docker run -d --name wallet-container -p 8080:8080 wallet
        "
