name: CI/CD Spring Boot con Docker

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del código
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Otorgar permisos de ejecución a gradlew
      run: chmod +x ./gradlew

    # Configuración de Java 17
    - name: Configurar Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Temurin es la distribución de Eclipse Adoptium de OpenJDK.
        java-version: '17'

    # Construcción con Gradle
    - name: Build con Gradle
      run: ./gradlew clean build

    # Construcción de la Imagen Docker
    - name: Construir imagen Docker
      run: docker build -t fabianyr/wallet:latest .

    # Login a Docker Hub y Publicación de la Imagen
    - name: Publicar imagen a Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag wallet:latest fabianyr/wallet:latest
        docker push fabianyr/wallet:latest

