name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Give exec permissions to gradlew
        run: chmod +x ./gradlew

      - name: Config Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build Docker image
        run: |
          docker build -t fabianyr/wallet:latest .
      - name: Publish image to docker hub
        run: docker push fabianyr/wallet:latest
  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Set user permissions for Docker
        run: |
            sudo usermod -aG docker ${USER}
            newgrp docker

      - name: Pull the image from docker
        run: docker pull fabianyr/wallet:latest
      - name: Remove old Docker Container
        run: docker rm -f wallet-container
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name wallet-container fabianyr/wallet:latest